---
- name: Stairmaster - Use Step CA to create certificates for a bunch of services on a bunch of servers
  hosts: all
  become: true
  gather_facts: true

  vars:
    step_version: "0.21.0"

    step_ca_server: step-ca.kemo.labs
    step_ca_port: 443
    # You can get the fingerprint from the Step CA Root CA Certificate
    # openssl x509 -in /root/.step/certs/root_ca.crt -noout -fingerprint -sha256
    step_ca_fingerprint: 12FEE0723035FEA0645146A6031EDF8F5F87409CA8BCA285FB779C8B2B528936

  tasks:
  - name: Read in the Site Configs
    include_vars:
      dir: "site-configs/{{ inventory_hostname }}"
      extensions:
        - yml
        - yaml

  - name: Download the Step CA CLI tools
    include_role:
      name: install-step-binaries
    vars:
      step_cli_version: "{{ step_version }}"

  - name: Bootstrap the host to trust the CA
    include_role:
      name: bootstrap-host
    vars:
      step_bootstrap_ca_url: "https://{{ step_ca_server }}:{{ step_ca_port }}"
      step_bootstrap_fingerprint: "{{ step_ca_fingerprint }}"
      step_cli_version: "{{ step_version }}"